# Generated by Django 2.2.7 on 2020-04-16 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
