# Generated by Django 2.2.7 on 2020-04-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_biz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='timestamp',
        ),
    ]
