# Generated by Django 2.2.7 on 2020-04-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200403_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='person',
            field=models.ForeignKey(default=1, on_delete='CASCADE ', to='quotes.Person'),
            preserve_default=False,
        ),
    ]
